import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';


final firestoreInstance = FirebaseFirestore.instance;

final userCollection = firestoreInstance.collection('users');
final roomCollection = firestoreInstance.collection('rooms');
final bookclubsCollection = firestoreInstance.collection('bookclubs');
final upcomingRoomsCollection = firestoreInstance.collection('upcomingRooms');

List users = [
  ///250
  // {"name" : "Naman Jain", "username" : "namanjain",},
  // {"name" : "Naman Gupta", "username" : "namangupta",},
  // {"name" : "Akash Tiwari", "username" : "akashtiwari",},
  // {"name" : "Shubham Tiwari", "username" : "shubhamtiwari",},
  // {"name" : "Shantanu Tiwari", "username" : "shantanu",},
  // {"name" : "Siddharth", "username" : "sidd",},
  // {"name" : "Nitin Jain", "username" : "nitinjain",},
  // {"name" : "Aman Jain", "username" : "aman jain",},
  // {"name" : "Parimal Gupta", "username" : "parimal",},
  // {"name" : "Alok Saxena", "username" : "saxenalok",},
  // {"name" : "Ram Kishor", "username" : "ramk",},
  // {"name" : "Nihal Pardeshi", "username" : "pardeshinihal",},
  // {"name" : "Mayur Banjara", "username" : "mayurban",},
  // {"name" : "Sanjana Birari", "username" : "sanjbirari",},
  // {"name" : "Mehek Chandel", "username" : "mehek",},
  // {"name" : "Varsha Singh", "username" : "varshsingh",},
  // {"name" : "Aradhya Verma", "username" : "vermaar",},
  // {"name" : "Kavya Keshav", "username" : "kavyakeshav",},
  // {"name" : "Monica Karma", "username" : "monikarma",},
  // {"name" : "Saurabh Karma", "username" : "karmasaurabh",},
  // {"name" : "Bedika Karmarkar", "username" : "karmarkarbedi",},
  // {"name" : "Bhawana Vyas", "username" : "bhawvyas",},
  // {"name" : "Bhushan Vittal", "username" : "vittalbhushan",},
  // {"name" : "Bhavesh", "username" : "bhaveyysh",},
  // {"name" : "Divya Singh", "username" : "divisingh",},
  // {"name" : "Santosh Mehra", "username" : "santoshmehra",},
  // {"name" : "Kaveri", "username" : "_kaveri_",},
  // {"name" : "Agasthya Shilpal", "username" : "agasthyapal",},
  // {"name" : "Anam Pal", "username" : "ampal",},
  // {"name" : "Niharika Jadhav", "username" : "_jadhavniharika_",},
  // {"name" : "Mayuri Kedare", "username" : "_yuri_",},
  // {"name" : "Jatin Verma", "username" : "jatinv",},
  // {"name" : "Paras Govind", "username" : "_paaras_",},
  // {"name" : "Akshar Vyas", "username" : "aksharvyas",},
  // {"name" : "Hitesh Dekhmukh", "username" : "hitesh_d",},
  // {"name" : "Devendra Purohit", "username" : "devpurohit",},
  // {"name" : "Mahira", "username" : "maahira",},
  // {"name" : "Devika Randhava", "username" : "deviran",},
  // {"name" : "Bhoomika Shirke", "username" : "bhoomishirke",},
  // {"name" : "Payal Joshi", "username" : "joshipayal",},
  // {"name" : "Neharika Pathak", "username" : "neharikapathak",},
  // {"name" : "Mayur Desai", "username" : "desaimayu",},
  // {"name" : "Bhavesh Mehra", "username" : "bhaveshmehra",},
  // {"name" : "Manthan Kumar", "username" : "mannyk",},
  // {"name" : "Ojas Sawant", "username" : "ojass",},
  // {"name" : "Tejas Mittal", "username" : "tejumittal",},
  // {"name" : "Ojaswini", "username" : "ojaswini",},
  // {"name" : "Eshika Devnagar", "username" : "eshikaa",},
  // {"name" : "Mayuri Rajpal", "username" : "mayuriraj",},
  // {"name" : "Akshata Singh", "username" : "akshata",},
  // {"name" : "Samiksha Sarthak", "username" : "samsarthak",},
  // {"name" : "Riya Matthew", "username" : "riyeah",},
  // {"name" : "Shreya Malik", "username" : "shreyaaah",},
  // {"name" : "Alex Mann", "username" : "alexenn",},
  // {"name" : "Raj Purohit", "username" : "rajrohit",},
  // {"name" : "Bhawana Chauhan", "username" : "bhawanah",},
  // {"name" : "Ramilla", "username" : "ramilla",},
  // {"name" : "Riya Sharma", "username" : "Riya",},
  // {"name" : "Anita Naik", "username" : "anitan",},
  // {"name" : "Anamika", "username" : "anamikaa",},
  // {"name" : "Kishor Rakesh", "username" : "KishOR",},
  // {"name" : "Ishita Solanki", "username" : "ishita",},
  // {"name" : "Radha Kishor", "username" : "radhakk",},
  // {"name" : "Vikram Vishwakarma", "username" : "vvikram",},
  // {"name" : "Kanav Mittal", "username" : "mittalkanav",},
  // {"name" : "Minal", "username" : "minal",},
  // {"name" : "Maya Chaturvedi", "username" : "mayac",},
  // {"name" : "Mathali", "username" : "mathali",},
  // {"name" : "Ali Aamir", "username" : "aalii",},
  // {"name" : "Pooman Panday", "username" : "poomanss",},
  // {"name" : "kajal Parihar", "username" : "kaajalp",},
  // {"name" : "Khushi Parihar", "username" : "khushhh",},
  // {"name" : "Karan Kumar", "username" : "karank",},
  // {"name" : "Rashi Bajpayee", "username" : "Raashii",},
  // {"name" : "Rashi Singh", "username" : "singhrashi",},
  // {"name" : "Dhanashree", "username" : "dhanashree",},
  // {"name" : "Kavya", "username" : "kaavvyy",},
  // {"name" : "Harshita Prajapati", "username" : "harshitap",},
  // {"name" : "Deepansh Parihar", "username" : "deepparihar",},
  // {"name" : "Vaibhav Nath", "username" : "Vaibhs",},
  // {"name" : "Vaibhavi Saket", "username" : "vebbz",},
  // {"name" : "Kanak Singh", "username" : "skanaks",},
  // {"name" : "Shivaji Rajat", "username" : "shivvani",},
  // {"name" : "Ketki", "username" : "ketki",},
  // {"name" : "Kritika", "username" : "kritika",},
  // {"name" : "Aditi Kashyap", "username" : "kashyap_adi",},
  // {"name" : "Sneha Kumar", "username" : "snehaa",},
  // {"name" : "Mihika", "username" : "mihika",},
  // {"name" : "Priyanka Naik", "username" : "naikpriyanka",},
  // {"name" : "Akansha Rajput", "username" : "akanshaa",},
  // {"name" : "Supriya Yadav", "username" : "suppriya",},
  // {"name" : "Lokesh Mangal", "username" : "loki",},
  // {"name" : "Rajas", "username" : "rajas",},
  // {"name" : "Yash Rana", "username" : "ranayash",},
  // {"name" : "Swati Singh", "username" : "swatii",},
  // {"name" : "Akash Rajput", "username" : "akki",},
  // {"name" : "Aayush Rajput", "username" : "rajput_aayush",},
  // {"name" : "Aparna Rajput", "username" : "apaharnaa",},
  // {"name" : "Kritika Waghmore", "username" : "Kritiw",},
  // {"name" : "Nikita Singh", "username" : "nikkita",},
  // {"name" : "Ankit Verma", "username" : "ankitverma",},
  // {"name" : "Prerna Singh", "username" : "prernasingh",},
  // {"name" : "Raj Shriwas", "username" : "shriwasraj",},
  // {"name" : "Devendra", "username" : "dev",},
  // {"name" : "Devika Saxena", "username" : "devvi",},
  // {"name" : "Amit Bhalla", "username" : "amitbhalla",},
  // {"name" : "Priyanka Singh", "username" : "priyankasingh",},
  // {"name" : "Aruna Jain", "username" : "arunajain",},
  // {"name" : "Harsh Patil", "username" : "harshpatil",},
  // {"name" : "Anshul Katiyar", "username" : "anshul",},
  // {"name" : "Renuka Shinde", "username" : "renuka",},
  // {"name" : "Akshat Singh", "username" : "akshat",},
  // {"name" : "Samrat Sen", "username" : "samratt",},
  // {"name" : "Nikhil Panday", "username" : "nikhilp",},
  // {"name" : "Sujal Arya", "username" : "sujal",},
  // {"name" : "Zaid", "username" : "zaid",},
  // {"name" : "Lalit Sharma", "username" : "lalit",},
  // {"name" : "Vikram", "username" : "vikram",},
  // {"name" : "Dev Dixit", "username" : "dixitdev",},
  // {"name" : "Sonia Dixit", "username" : "sona",},
  // {"name" : "Krishangi Dubey", "username" : "dubey",},
  // {"name" : "Ishaan Jain", "username" : "ishaaan",},
  // {"name" : "Neha Patil", "username" : "patilneha09",},
  // {"name" : "Yash Kumar", "username" : "yashkumar",},
  // {"name" : "Om Jain", "username" : "Ommie",},
  // {"name" : "Harsh Singh", "username" : "harshshingh",},
  // {"name" : "Megha", "username" : "megha123",},
  // {"name" : "Narayan Dev", "username" : "narayan",},
  // {"name" : "Ajinkya Patil", "username" : "ajinkya",},
  // {"name" : "Armaan Gupta", "username" : "armann",},
  // {"name" : "Chintamani Shelar", "username" : "chintamani",},
  // {"name" : "Cheshtha Saket", "username" : "cheshthaa",},
  // {"name" : "Mihika Mahajan", "username" : "mihikamahajan",},
  // {"name" : "Parth Deshmukh", "username" : "dparth",},
  // {"name" : "Sahil Signh", "username" : "saahil",},
  // {"name" : "Sahil Lokesh", "username" : "sahilok",},
  // {"name" : "Rajdeep Maheshwari", "username" : "rajdeepm",},
  // {"name" : "Deepa Maheshwari", "username" : "maheshwarideepa",},
  // {"name" : "Mayur Nikam", "username" : "mayurnikam",},
  // {"name" : "Pritam Diwan", "username" : "pritam",},
  // {"name" : "Payal Kushwaha", "username" : "payalkush",},
  // {"name" : "Manaswi Rathor", "username" : "manrathor",},
  // {"name" : "Rohan Roy", "username" : "royrohan",},
  // {"name" : "Akash Pillai", "username" : "akashpillai",},
  // {"name" : "Sagar Chandrawanshi", "username" : "_sagar_",},
  // {"name" : "Yogita Soni", "username" : "yogi_soni",},
  // {"name" : "Rajesh Yadav", "username" : "rajyadav",},
  // {"name" : "Farida Husain", "username" : "faaraah",},
  // {"name" : "Mitesh Nair", "username" : "miteshnair",},
  // {"name" : "Akhikesh Yadav", "username" : "akhiyadav",},
  // {"name" : "Pooja Khandapal", "username" : "khandapalpooja",},
  // {"name" : "Nishant Sen", "username" : "nishant",},
  // {"name" : "Kanav Mehra", "username" : "kanav",},
  // {"name" : "Siddharth Shukla", "username" : "sidd",},
  // {"name" : "Deepanshu Verma", "username" : "deVerma",},
  // {"name" : "Kirti Dayama", "username" : "thekirti",},
  // {"name" : "Neha Balchandani", "username" : "Nehab",},
  // {"name" : "Sonal Parihar", "username" : "sonall",},
  // {"name" : "Manish Kehlani", "username" : "kehlanimanish",},
  // {"name" : "Raj More", "username" : "themore",},
  // {"name" : "Mridula Arihar", "username" : "mridulaar",},
  // {"name" : "Aayushi Soni", "username" : "aaayushi",},
  // {"name" : "Aayushi Vyas", "username" : "ishivyas",},
  // {"name" : "Aditi Dubey", "username" : "adidubey",},
  // {"name" : "Devayush Kiran", "username" : "dev_aayush",},
  // {"name" : "Sanjana Baviskar", "username" : "sanajanaa",},
  // {"name" : "Praveen Katiyar", "username" : "praveeen",},
  // {"name" : "Irene Matthew", "username" : "irene",},
  // {"name" : "Neha Suneja", "username" : "nenss",},
  // {"name" : "Kashish", "username" : "kashish",},
  // {"name" : "Devi Rajas", "username" : "devi.ne",},
  // {"name" : "Akansha Sharma", "username" : "akansha",},
  // {"name" : "Novu Kumar", "username" : "knov",},
  // {"name" : "Abhishek Verma", "username" : "abhiv",},
  // {"name" : "Krish Pande", "username" : "kpande",},
  // {"name" : "Sonal Dahare", "username" : "_sonal_",},
  // {"name" : "Sonia Rahane", "username" : "soso_rahane",},
  // {"name" : "Jenny Roy", "username" : "jenroy",},
  // {"name" : "Nilesh Shrivastava", "username" : "nileshhs",},
  // {"name" : "Pooja Parihar", "username" : "poojaa",},
  // {"name" : "Divya Sharma", "username" : "d_sha",},
  // {"name" : "Vibha Vergese", "username" : "VVergese",},
  // {"name" : "Sourabh Yadav", "username" : "_s_yadav_",},
  // {"name" : "Abhinav Shukla", "username" : "abhi_shukla",},
  // {"name" : "Rehaan Gupta", "username" : "rehaaahn",},
  // {"name" : "Aarzoo Gupta", "username" : "arzozo",},
  // {"name" : "Priyanka Gandhi", "username" : "priyagan",},
  // {"name" : "Naina Arya", "username" : "arya_naina",},
  // {"name" : "Jyotsna Verma", "username" : "jyotsnav",},
  // {"name" : "Dolly Jagtap", "username" : "djagtap",},
  // {"name" : "Surbhi", "username" : "surbhi",},
  // {"name" : "Kavya Mangala", "username" : "Kavyyy",},
  // {"name" : "Zobena Gia", "username" : "zobiia",},
  // {"name" : "Kanak Jain", "username" : "kanakjain",},
  // {"name" : "Maya Aamir", "username" : "mayya",},
  // {"name" : "Sanika Seikh", "username" : "sanikaa",},
  // {"name" : "Sneha Solanki", "username" : "snehasolanki",},
  // {"name" : "Samarth Sen", "username" : "samsen",},
  // {"name" : "Pooja Banerjee", "username" : "poojajee",},
  // {"name" : "Farhaan Riyaaz", "username" : "farhaan",},
  // {"name" : "Chetna Lokhande", "username" : "lokhandechetna",},
  // {"name" : "Kriya Kapoor", "username" : "kkriyaa",},
  // {"name" : "Neha Tripathi", "username" : "nehatripathi",},
  // {"name" : "Anjali Sonaji", "username" : "sosoanjali",},
  // {"name" : "Yash Sharma", "username" : "yasharma",},
  // {"name" : "Mansi More", "username" : "Maansii",},
  // {"name" : "Rutuja Patil", "username" : "rutupatil",},
  // {"name" : "Prateek Pal", "username" : "pratick",},
  // {"name" : "Prerna Purohit", "username" : "prernahere",},
  // {"name" : "Paras Rajput", "username" : "paras",},
  // {"name" : "Ishita Vyas", "username" : "ishitavyas",},
  // {"name" : "Navya Mishra", "username" : "navyam",},
  // {"name" : "Riya Thomas", "username" : "riya",},
  // {"name" : "Sana Mehra", "username" : "sanam",},
  // {"name" : "Rishubh Kumar", "username" : "rishik",},
  // {"name" : "Neha Mann", "username" : "nemmei",},
  // {"name" : "Nihal Raj", "username" : "teareader",},
  // {"name" : "Neha Mann", "username" : "nemmei",},
  // {"name" : "Rashmi Patel", "username" : "prashmi",},
  // {"name" : "Neha Mann", "username" : "nemmei",},
  // {"name" : "Meera", "username" : "meera",},
  // {"name" : "Priya Jain", "username" : "pj",},
  // {"name" : "Kirti Rai", "username" : "raikirti",},
  // {"name" : "Shraddha Kaushik", "username" : "kshrahh",},
  // {"name" : "Sumit Rai", "username" : "summr",},
  // {"name" : "Aadil Khan", "username" : "aaadil",},
  // {"name" : "Chaitanya Rathi", "username" : "chaitanya",},
  // {"name" : "Akhilesh", "username" : "akhilesh",},
  // {"name" : "Akshay Chabra", "username" : "akki_chabra",},
  // {"name" : "Amit Joshi", "username" : "joshiamit",},
  // {"name" : "Anil Jones", "username" : "aniljones",},
  // {"name" : "Deepak Gupta", "username" : "deep",},
  // {"name" : "Aastha Jain", "username" : "aastha",},
  // {"name" : "Priya Singh", "username" : "singhpriya",},
  // {"name" : "Tanuj Pathak", "username" : "taanujj",},
  // {"name" : "Sejal Raizada", "username" : "raisejal",},
  // {"name" : "Pooman Patil", "username" : "poohnam",},
  // {"name" : "Dhruv Jain", "username" : "dhruv",},
  // {"name" : "Dolly Verma", "username" : "dollie",},
  // {"name" : "Nikita Singh", "username" : "nikki",},
  // {"name" : "Ekta Gandhi", "username" : "ektag",},
  // {"name" : "Mitali Priya", "username" : "mipriya",},
  // {"name" : "Samar Jain", "username" : "samar",},
  // {"name" : "Nidhi Prajapati", "username" : "nidzo",},
  // {"name" : "Tanvi Mandrai", "username" : "tanviz",},
  // {"name" : "Zoya", "username" : "zoya",},
  // {"name" : "Sania Saxena", "username" : "saniania",},
  // {"name" : "Rishikesh Mahi", "username" : "mahirishikesh",},
  // {"name" : "Akshat Jain", "username" : "akshat",},
  // {"name" : "Purva Deshmukh", "username" : "purvadesh",},
  // {"name" : "Prachi Jain", "username" : "prachij",},
  // {"name" : "Aman Soni", "username" : "amanns",}
];

List genres = [
  // "Action and Adventure",
  // "Biographies and Autobiographies",
  // "Classics",
  // "Comic Book",
  // "Cookbooks",
  // "Detective and Mystery",
  // "Essays",
  // "Fantasy",
  // "Historical Fiction",
  // "Horror",
  // "Literary Fiction",
  // "Memoir",
  // "Poetry",
  // "Romance",
  // "Science Fiction (Sci-Fi)",
  // "Short Stories",
  // "Suspense and Thrillers",
  // "Self-Help",
  // "True Crime",
  // "Women's Fiction"
];

List topReads = [
  // {"book_name" : "IT", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2FIT.jpeg?alt=media&token=1da6492f-2f42-4642-961b-1ea1bb9e38bb" },
  // {"book_name" : "A Hunger Like No Other", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fa_hunger_like_no_other.jpeg?alt=media&token=d2efcb4d-55dc-4da5-8091-c4bf684ed6f8" },
  // {"book_name" : "A Kingdom Of Dream", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fa_kingdom_of_dreams.jpeg?alt=media&token=cec3d3a1-6e30-4c48-a6b2-19d6be2c0c48" },
  // {"book_name" : "A Man Called Ove", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fa_man_called_ove.jpeg?alt=media&token=9bbdb393-59e0-4296-a3ae-2e8ab914a342" },
  // {"book_name" : "As Old As Time", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fas_old_as_time.jpeg?alt=media&token=868cfa94-25c1-40da-b244-1d231d617156" },
  // {"book_name" : "Book Of Night", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fbook_of_night.jpeg?alt=media&token=244c56ae-edef-43a7-99cf-f8e9b58a711c" },
  // {"book_name" : "Chi Boy", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fchi_boy.jpeg?alt=media&token=b403c7c4-1ea4-4c59-b50c-54bddfc799a3" },
  // {"book_name" : "Circe", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fcirce.jpeg?alt=media&token=9b0d7a5d-2e98-4bd3-bc29-f53d55bc346c" },
  // {"book_name" : "Cover Story", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fcover_story.jpeg?alt=media&token=3f75ec99-b44a-4ca9-8ed5-58d1ac996c6d" },
  // {"book_name" : "Darkness Fade", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fdarkness_fade.png?alt=media&token=dca50f2d-3e91-416f-ba05-b65a65fc06ff" },
  // {"book_name" : "Don't Call The Wolves", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fdont_call_the_wolf.jpeg?alt=media&token=52d228b5-8621-4a9a-9be0-4ea3943ce66b" },
  // {"book_name" : "Don't Make Me Think", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fdont_make_me_think.jpeg?alt=media&token=4ee147ca-c040-4976-8a61-285b844091a1" },
  // {"book_name" : "From Below", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Ffrom_below.jpeg?alt=media&token=19b0ac41-bf06-4bcd-a4dc-d9afb69c272b" },
  // {"book_name" : "Gardens Of The Moons", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fgardens_of_the_moon.jpeg?alt=media&token=afb90866-5124-4562-b621-99b2070e52be" },
  // {"book_name" : "Golden", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fgolden.jpeg?alt=media&token=81d5644e-46b6-4d74-9b1f-9489cc2d3628" },
  // {"book_name" : "Hooked", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fhooked.png?alt=media&token=30fe85a6-aff2-4f39-a847-2274964882ac" },
  // {"book_name" : "I'll Give You The Sun", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fill_give_you_the_sun.jpeg?alt=media&token=9e569f99-3e2f-44e7-8fc6-38ee097283d7" },
  // {"book_name" : "Last Child In The Woods", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Flast_child_in_the_woods.jpeg?alt=media&token=28b71c28-e749-4d41-85dc-ae44c57abf52" },
  // {"book_name" : "Life After Life", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Flife_after_life.jpeg?alt=media&token=38f5488f-1459-4749-9945-3f3f211e9256" },
  // {"book_name" : "Life As We Made It", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Flife_as_we_made_it.jpeg?alt=media&token=06f06db8-17e0-489a-a22d-ddeac7cd8213" },
  // {"book_name" : "Mad Honey", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fmad_honey.jpeg?alt=media&token=2514706f-eac0-4187-98b1-4035414ccfce" },
  // {"book_name" : "Malibu Rising", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fmalibu_rising.jpeg?alt=media&token=3382db9c-ca6f-4e42-ae34-05dbfc93a179" },
  // {"book_name" : "Milk And Honey", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fmilk_and_honey.jpeg?alt=media&token=1856f237-a934-456e-a317-053467a5e2a1" },
  // {"book_name" : "More Than You'll Ever Know", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fmore_than_youll_ever_know.jpeg?alt=media&token=b0423332-9f32-4ad9-8d9a-7798131b1afa" },
  // {"book_name" : "Next Patient Please", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fnext_patient_please.jpeg?alt=media&token=85d27063-e1b6-4d86-b3d8-cadec3cf1fff" },
  // {"book_name" : "Now What", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fnow_what.jpeg?alt=media&token=97ccc0a9-097d-49c6-915d-86808709186a" },
  // {"book_name" : "Once There Were Wolves", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fonce_there_were_wolves.jpeg?alt=media&token=221d9564-115b-4872-828d-4bc14f1182c6" },
  // {"book_name" : "Poor Little Amy", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fpoor_little_amy.jpeg?alt=media&token=eb859c88-89ab-4cd3-aff7-58dc0fed61fa" },
  // {"book_name" : "Psychology Of Money", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fpsychology_of_money.jpeg?alt=media&token=231285ad-9d5f-4894-941d-ae091733bc4c" },
  // {"book_name" : "Reculturing", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Freculturing.jpeg?alt=media&token=8061019d-3856-4d37-ae84-98d2eac8a65a" },
  // {"book_name" : "Remote Control", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fremote_control.jpeg?alt=media&token=620676f0-30ce-4a37-8aad-e26e89b7c213" },
  // {"book_name" : "See No Stranger", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fsee_no_stranger.jpeg?alt=media&token=64244f93-19e9-4208-bfd7-4df5c3fb8fa9" },
  // {"book_name" : "So This Is Love", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fso_this_is_love.jpeg?alt=media&token=169891fa-31ab-4d37-b289-b3b962d7df12" },
  // {"book_name" : "Still Me", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fstill_me.jpeg?alt=media&token=ce64492d-f691-4948-8e3a-9588d3b57bb8" },
  // {"book_name" : "Straight On Till Morning", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fstraight_on_till_morning.jpeg?alt=media&token=aa1d7f42-4e5b-444a-9cf2-a6803ec9c93d" },
  // {"book_name" : "Summer Bird Blue", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fsummer_bird_blue.jpeg?alt=media&token=e80e8f6a-ca08-440e-8914-cc6d36e3d5bf" },
  // {"book_name" : "The Angel Of Rome", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_angel_of_rome.jpeg?alt=media&token=792285fc-a5e6-4d1e-b1ac-b02b68311648" },
  // {"book_name" : "The Book Of Two Ways", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_book_of_teo_ways.jpeg?alt=media&token=b4dbc2ad-2ddd-47ba-a22f-02015d8ec53e" },
  // {"book_name" : "The Book Thief", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_book_thief.jpeg?alt=media&token=a0aec560-636e-451b-82db-d498254fefdf" },
  // {"book_name" : "The Edge Of The Universe", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_edge_of_the_universe.jpeg?alt=media&token=cb8dab56-4271-4a83-88b2-d1c9e80921f0" },
  // {"book_name" : "The Foundling", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_foundling.jpeg?alt=media&token=81ec03ab-5a74-4a52-986a-ec6a67a536bd" },
  // {"book_name" : "The Grace Of Kings", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_grace_of_kings.jpeg?alt=media&token=90366c23-d85c-4760-84c8-ab7c1061a51f" },
  // {"book_name" : "The Hacienda", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_hacienda.jpeg?alt=media&token=4c5816de-8ef7-493c-ab8c-67d6d2b54d51" },
  // {"book_name" : "The Hating Game", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_hating_game.jpeg?alt=media&token=ec66f7a7-c7b3-428d-9a95-bdd76d745e04" },
  // {"book_name" : "The Last Thing He Told Me", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_last_thing_he_told_me.jpeg?alt=media&token=70c18942-f7ef-457a-85f1-8d48834e5806" },
  // {"book_name" : "The Little Dog", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_little_dog.jpeg?alt=media&token=7eee9582-2e46-4f9c-998c-b7470eb97ea4" },
  // {"book_name" : "The Luminaries", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_luminaries.jpeg?alt=media&token=a1345681-f494-41ff-8dcd-fb580794991f" },
  // {"book_name" : "The Maid", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_maid.jpeg?alt=media&token=ec245ecb-5db3-4e48-b409-141a2472eaf7" },
  // {"book_name" : "The Midnight Library", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_midnight_library.jpeg?alt=media&token=d75febac-ca0a-45a6-a3eb-5f5491c84eb3" },
  // {"book_name" : "the Night Tiger", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_night_tiger.jpeg?alt=media&token=289e7cf6-6070-4e14-b2bf-6fd7d9a90d33" },
  // {"book_name" : "The Richest Man In Babylon", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_richest_man_in_babylon.jpeg?alt=media&token=8681e8d3-3d80-40a5-8e26-edd3c10c4471" },
  // {"book_name" : "The River You Touch", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_river_you_touch.jpeg?alt=media&token=bc48ddba-0824-485e-94de-eab291c01172" },
  // {"book_name" : "The Roma", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_roma.jpeg?alt=media&token=d4fb91a9-ef28-4f7c-bbe8-0b86a8a4c433" },
  // {"book_name" : "The Roughest Draft", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_roughest_draft.jpeg?alt=media&token=eaae15ba-910b-46c7-b9cb-2eba3c97315f" },
  // {"book_name" : "The Silent Patient", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_silent_patient.jpeg?alt=media&token=7a4bf39c-b19f-412a-8645-b66a4d04b764" },
  // {"book_name" : "The Unknowns", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_unknowns.jpeg?alt=media&token=9d3e83d2-d5dd-4220-8824-7f6ba5cb6572" },
  // {"book_name" : "The Wise Man's Fear", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fthe_wise_mans_fear.jpeg?alt=media&token=f6e34d23-df21-4e89-930e-e3574905a31e" },
  // {"book_name" : "To Kill A Mockingbird", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fto_kill_a_mockingbird.jpeg?alt=media&token=22ccf039-da06-4e71-b67d-5d229df46bb2" },
  // {"book_name" : "Twisted Games", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Ftwisted_games.jpeg?alt=media&token=27e83de1-1129-4d7a-828c-93b70a367c38" },
  // {"book_name" : "Ugly Love", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fugly_love.jpeg?alt=media&token=ab453de1-e623-47b4-b7da-e5e68a798256" },
  // {"book_name" : "Velvet Was The Night", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fvelvet_was_the_night.jpeg?alt=media&token=8047aed8-0e9f-48af-85a7-d0346d73061f" },
  // {"book_name" : "When The World Went Dark", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fwhen_the_world_went_dark.jpeg?alt=media&token=5ca04aa2-0d15-4f99-a155-cedd081e440f" },
  // {"book_name" : "Wild", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fwild.jpeg?alt=media&token=cbc12f8e-9660-47fa-b3c3-ce76484d67e1" },
  // {"book_name" : "Wintering", "image_link" : "https://firebasestorage.googleapis.com/v0/b/fostr2021.appspot.com/o/books%2Fwintering.jpeg?alt=media&token=dc2813f3-b778-4818-bef0-bb87a5712d56" },
];

List bio = [
  // "The more that you read, the more things you will know. The more that you learn, the more places you’ll go",
  // "Reading brings us unknown friends.",
  // "There is more treasure in books than in all the pirate's loot on Treasure Island.",
  // "Make it a rule never to give a child a book you would not read yourself.",
  // "A book is a gift you can open again and again.",
  // "Outside of a dog, a book is a man’s best friend. Inside of a dog, it’s too dark to read.",
  // "Think before you speak. Read before you think.",
  // "Reading is a discount ticket to everywhere.",
  // "We read in bed because reading is halfway between life and dreaming, our own consciousness in someone else’s mind.",
  // "My alma mater was books, a good library…. I could spend the rest of my life reading, just satisfying my curiosity.",
  // "Books are a uniquely portable magic.",
  // "Books and doors are the same thing. You open them, and you go through into another world.",
  // "Books are mirrors: you only see in them what you already have inside you.",
  // "A book is a way for your imagination to be wild and free.",
  // "Take a good book to bed with you – books do not snore.",
  // "A well-read woman is a dangerous creature.",
  // "I think books are like people, in the sense that they’ll turn up in your life when you most need them.",
  // "A reader lives a thousand lives before he dies . . . The man who never reads lives only one.",
  // "There is no frigate like a book to take us lands away.",
  // "No. I can survive well enough on my own – if given the proper reading material.",
  // "When you lose yourself in a book the hours grow wings and fly.",
  // "The world belongs to those who read.",
  // "Reading one book is like eating one potato chip.",
  // "To know a man’s library is, in some measure, to know a man’s mind.",
  // "If you don’t like to read, you haven’t found the right book.",
  // "Never put off till tomorrow the book you can read today.",
  // "Read a thousand books, and your words will flow like a river.",
  // "Reading is an intelligent way of not having to think.",
  // "A good book is an event in my life.",
  // "Reading well is one of the great pleasures that solitude can afford you.",
  // "The reading of all good books is like a conversation with the finest minds of past centuries.",
  // "No two persons ever read the same book.",
  // "Books serve to show a man that those original thoughts of his aren’t very new after all.",
  // "The library is inhabited by spirits that come out of the pages at night.",
  // "Until I feared I would lose it, I never loved to read. One does not love breathing.",
  // "A peasant that reads is a prince in waiting.",
  // "Books are both our luxuries and our daily bread.",
  // "I have always imagined that paradise will be a kind of library.",
  // "These books gave Matilda a hopeful and comforting message: You are not alone.",
  // "Once upon a time’ is one of the most magical phrases you’ll ever read.",
  // "Oh, magic hour, when a child first knows she can read printed words!",
  // "Reading should not be presented to children as a chore, a duty. It should be offered as a gift.",
  // "Not all readers are leaders, but all leaders are readers.",
  // "I do not read a book; I hold a conversation with the author.",
  // "A book is a version of the world. If you do not like it, ignore it; or offer your own version in return.",
  // "There are worse crimes than burning books. One of them is not reading them.",
  // "Don’t get into a relationship with someone who doesn’t own any books.",
  // "Never trust anyone who has not brought a book with them.",
  // "Man reading should be man intensely alive. The book should be a ball of light in one’s hand.",
  // "Let’s be reasonable and add an eighth day to the week that is devoted exclusively to reading.",
  // "The end’ is one of the saddest sentences you’ll ever come across.",
  // "Reading is departure and arrival.",
  // "Whenever you read a good book, somewhere in the world a door opens to allow in more light.",
  // "Some books leave us free and some books make us free.",
  // "Reading gives us someplace to go when we have to stay where we are.",
  // "I have always imagined paradise as a kind of library.",
  // "Children know perfectly well that unicorns aren’t real, but they also know that books about unicorns, if they are good books, are true books.",
  // "Books should go where they will be most appreciated, and not sit unread, gathering dust on a forgotten shelf, don’t you agree",
  // "The world was hers for the reading.",
  // "Putting down a good book can almost be an impossible act to do.",
  // "Some books should be tasted, some devoured, but only a few should be chewed and digested thoroughly",
  // "I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book! — When I have a house of my own, I shall be miserable if I have not an excellent library.",
  // "You know you’ve read a good book when you turn the last page and feel a little as if you have lost a friend.",
  // "Rainy days should be spent at home with a cup of tea and a good book.",
  // "Reading is an exercise in empathy; an exercise in walking in someone else’s shoes for a while.",
  // "If there is a book that you want to read, but it hasn’t been written yet, you must be the one to write it",
  // "Books are good company, in sad times and happy times, for books are people – people who have managed to stay alive by hiding between the covers of a book.",
  // "Each book was a world unto itself, and in it I took refuge.",
  // "I love the smell of book ink in the morning.",
  // "You can never get a cup of tea large enough or a book long enough to suit me.",
  // "A book is a garden, an orchard, a storehouse, a party, a company by the way, a counselor, a multitude of counselors.",
  // "To learn to read is to light a fire; every syllable that is spelled out is a spark.",
  // "For my whole life, my favorite activity was reading. It’s not the most social pastime.",
  // "Reading is an active, imaginative act; it takes work.",
  // "I always read. You know how sharks have to keep swimming or they die? I’m like that. If I stop reading, I die.",
  // "Books are things of fiction that seem like reality.",
  // "Think of this – that the writer wrote alone, and the reader read alone, and they were alone with each other.",
  // "Once you have read a book you care about, some part of it is always with you.",
  // "You have to remember that it is impossible to commit a crime while reading a book",
  // "Show me a family of readers, and I will show you the people who move the world.",
  // "Reading – even browsing  – an old book can yield sustenance denied by a database search",
  // "Reading makes immigrants of us all. It takes us away from home, but more important, it finds homes for us everywhere.",
  // "Reading is essential for those who seek to rise above the ordinary.",
  // "It is a great thing to start life with a small number of really good books which are your very own.",
  // "What a blessing it is to love books",
  // "No entertainment is so cheap as reading, nor any pleasure so lasting.",
  // "If you’re looking for some magic in your life, open up a book.",
  // "There are many little ways to enlarge your world. Love of books is the best of all.",
  // "A great book should leave you with many experiences, and slightly exhausted at the end. You live several lives while reading",
  // "One glance at a book and you hear the voice of another person, perhaps someone dead for 1,000 years. To read is to voyage through time.",
  // "Books are the plane, and the train, and the road. They are the destination, and the journey. They are home.",
  // "What kind of life can you have in a house without books?",
  // "Once you learn to read, you will be forever free",
  // "Reading… a vacation for the mind…",
  // "Reading is to the mind what exercise is to the body.",
  // "It is better to know one book intimately than a hundred superficially.",
  // "To acquire the habit of reading is to construct for yourself a refuge from almost all the miseries of life.",
  // "Classic’ – a book which people praise and don’t read.",
  // "Keep reading. It’s one of the most marvelous adventures that anyone can have.",
  // "Always read something that will make you look good if you die in the middle of it.",
  // "Books are the movies of our minds.",
];
